### ISSUE TITLE
Excessive 'MyApp wants to open ...' dialogs displayed during wallet selection (iOS)

### ISSUE THREAD

**Issue by ozgurrgul** [reown-com/appkit-react-native#234] opened 2024-09-16 11:41 UTC
**Describe the bug**
During wallet selection, sometimes 'MyApp wants to open ...' dialog shown excessive times. This doesn't happen always.

**SDK Version (if relevant)**
``` json
"@tanstack/react-query": "^5.52.2",
"@walletconnect/react-native-compat": "2.15.1",
"@web3modal/wagmi-react-native": "^2.0.2",
"wagmi": "^2.12.7",
"@react-native-community/netinfo": "6.0.0",
"react-native-get-random-values": "^1.11.0",
```

**To Reproduce**
1. Go to 'WalletConnect'

**Expected behavior**
It should only show dialog once

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: 17

**Additional context**
This problem occurs when we call ` web3Modal.open({ view: 'Connect' });` method and rest is handled by WalletConnect. Problem can be seen in the video:

https://github.com/user-attachments/assets/9abdcf8a-5503-40d5-9793-aacfbe06ae32

WalletConnectProvider.tsx:
``` tsx
import { WagmiProvider } from 'wagmi';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createWeb3Modal, defaultWagmiConfig, Web3Modal } from '@web3modal/wagmi-react-native';
import React, { ReactNode } from 'react';
import { WALLET_CONNECT_PROJECT_ID } from '~/shared/environment';
import { mainnet, polygon, bsc, avalanche } from '@wagmi/core/chains';

const SUPPORTED_CHAIN_CONFIGS = [mainnet, polygon, bsc, avalanche] as const;
export const WALLET_CONNECT_METADATA: ConfigOptions['metadata'] = {
  name: 'Bitvavo',
  description: 'Connect your wallet',
  url: 'https://bitvavo.com/',
  icons: ['https://bitvavo.com/press/blue/bitvavo-mark/bitvavo-mark-blue.png'],
  redirect: {
    native: `${NAVIGATION_SCHEMA}://`
  }
};

const queryClient = new QueryClient();

const wagmiConfig = defaultWagmiConfig({
  chains: SUPPORTED_CHAIN_CONFIGS,
  projectId: WALLET_CONNECT_PROJECT_ID,
  metadata: WALLET_CONNECT_METADATA
});

createWeb3Modal({
  projectId: WALLET_CONNECT_PROJECT_ID,
  wagmiConfig,
  enableAnalytics: false
});

export const WalletConnectProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        {children}
        <Web3Modal />
      </QueryClientProvider>
    </WagmiProvider>
  );
};
```

WalletConnect.tsx;
``` tsx
import React from 'react';
import { Web3Modal } from '@web3modal/wagmi-react-native';
import { Steps } from '../ui/Steps';
import { WalletConnectProvider } from './WalletConnectProvider';
import { useWalletConnectConnectionManager } from './useWalletConnectConnectionManager';

const WalletConnectInner = () => {
  const {
    open,
    isConnected,
    disconnect: wcDisconnect,
    sign: wcSign,
    address,
    loading
  } = useWalletConnectConnectionManager();


  const sign = async () => {
    if (!address) return;
    const signature = await wcSign();
    if (!signature) return;
    // omitted
  };

  const disconnect = () => {
    wcDisconnect();
  };

  const getContent = () => {
    if (loading) {
      return <Steps.Loading />;
    }
    if (isConnected) {
      return <Steps.Connected onPressOpenWallet={sign} onPressDisconnect={disconnect} />;
    }

    return <Steps.NotConnected onPressOpenWallet={open} />;
  };

  return (
    <WalletConnectProvider>
      {getContent()}
      <Web3Modal />
    </WalletConnectProvider>
  );
};

export const WalletConnect = () => {
  return (
    <WalletConnectProvider>
      <WalletConnectInner />
    </WalletConnectProvider>
  );
};
```

useWalletConnectConnectionManager.ts:
``` tsx
import { useWeb3Modal } from '@web3modal/wagmi-react-native';
import { useDisconnect, useAccount, useSignMessage } from 'wagmi';

export const useWalletConnectConnectionManager = () => {
  const web3Modal = useWeb3Modal();
  const mDisconnect = useDisconnect();
  const account = useAccount();
  const { signMessageAsync } = useSignMessage();
  const { isConnected } = account;
  const selectedChain = account.chain;

  const open = () => {
    web3Modal.open({ view: 'Connect' });
  };

  const disconnect = () => {
    mDisconnect.disconnect();
  };

  const sign = async () => {
    try {
      const sig = await signMessageAsync({ message: 'Test' });

      return sig;
      // eslint-disable-next-line no-empty
    } catch (e) {
      return null;
    }
  };

  return {
    isConnected,
    loading: account.isConnecting || account.isReconnecting,
    selectedChain,
    address: account.address,
    open,
    disconnect,
    sign
  };
};

```

Some logs appearing in case it helps:
``` bash
Warning: Encountered two children with the same key, `f2436c67184f158d1beda5df53298ee84abfc367581e4505134b5bcf5f46697d:e9ff15be73584489ca4a66f64d32c4537711797e30b6660dbcb71ea72a42b1f4:bc949c5d968ae81310268bf9193f9c9fb7bb4e1283e1284af8f2bd4992535fd6:ef333840daf915aafdc4a004525502d6d49d77bd9c65e0642dbaefb3c2893bef`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version. 
Warning: Encountered two children with the same key, `9414d5a85c8f4eabc1b5b15ebe0cd399e1a2a9d35643ab0ad22a6e4a32f596f0:84b43e8ddfcd18e5fcb5d21e7277733f9cccef76f7d92c836d0e481db0c70c04:18450873727504ae9315a084fa7624b5297d2fe5880f0982979c17345a138277:fd20dc426fb37566d803205b19bbc1d4096b248ac04548e3cfb6b3a38bd033aa`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.  
  
Task orphaned for request <NSMutableURLRequest: 0x305be9d80> { URL: data:image/webp;base64,UklGRsgQAABXRUJQVlA4ILwQAABQcgCdASqQAZABPkkkjkUioiEUKXx8KASEs7d4BNpW9CZkpB8Z9W19e3P8zgHpdMFzoj0P+ ... AAAAAAA= }
Task orphaned for request <NSMutableURLRequest: 0x305be9bc0> { URL: data:image/webp;base64,UklGRlQUAABXRUJQVlA4IEgUAABwdgCdASqQAZABPkkkkUWioiITC0QoKASEsrdz2QUiPEDmJQwum5L8xoKMRfc6pY9h+YHv+ ... F7AAAA== }
Task orphaned for request <NSMutableURLRequest: 0x305be9bb0> { URL: data:image/webp;base64,UklGRiIIAABXRUJQVlA4WAoAAAAQAAAAjwEAjwEAQUxQSMEEAAABoATb2uI2+lrdGZLkckvtMCdaucIsexVTOHGytIMqr1OcK ... AAAAAAA= }
Task orphaned for request <NSMutableURLRequest: 0x305be9b80> { URL: data:image/webp;base64,UklGRjYRAABXRUJQVlA4ICoRAAAQYgCdASqQAZABPkkkkUWioiGSKjQ0KASEsrd+M/y3Yz9adfKhid/4j+4/tn4jlJO2f2T9r ... AAAAAA== }
 
[MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit]
```

**Comment by ozgurrgul** [comment] 2024-09-16 18:10
I bumped the versions as instructed but unfortunately the same issue still persists when I test.

**Comment by ignaciosantise** [comment] 2024-09-16 18:19
Okey, can you check just having one `Web3Modal` component? If you want to use the modal in two or more views, you should put it in the root view of your app

**Comment by ignaciosantise** [comment] 2024-09-18 15:13
any news @ozgurrgul ?

**Comment by ozgurrgul** [comment] 2024-09-19 15:38
hi @ignaciosantise, good catch I didn't notice `WalletConnectProvider` was used in 2 place

I moved `WalletConnectProvider` to our root, this issue still continues. 

I also tried using `W3mButton` only to see if it solves, but still same.

Interesting things is this issue only happen on our prod build and not locally. I am not able to replicate the issue on our developer build in the same phone. 

Also, this issue doesn't happen for every wallet. For example for Trust Wallet/Metamask I don't see this issue but for Rainbow/OKX it happens every time.

**Comment by ignaciosantise** [comment] 2024-09-19 16:45
okey, it's really weird. I cannot reproduce on our sample apps from Testflight. Does it also happen on Android? Which version of react native are you using?

**Comment by ozgurrgul** [comment] 2024-09-23 07:08
I am not able to reproduce this issue on Android (at least for Rainbow wallet case).

**Comment by ignaciosantise** [comment] 2024-09-23 13:02
@ozgurrgul could you create a minimal reproducible example? So i can try to reproduce it locally.

Can you also add a log [here](https://github.com/reown-com/appkit-react-native/blob/ffedfdd8a1e5e60a4c78f18046a47dd07c899638/packages/scaffold/src/partials/w3m-connecting-mobile/index.tsx#L73)? That code should be executed once, but it seems it's entering in a loop 🤔

**Comment by ignaciosantise** [comment] 2024-10-17 18:33
hey @ozgurrgul 👋  can you provide a minimal reproducible example?

**Comment by ozgurrgul** [comment] 2024-10-25 10:38
HI @ignaciosantise, sorry I was AFK due to to personal reasons.

> could you create a minimal reproducible example? So i can try to reproduce it locally.
I have tried to create a reproducible example and I wasn't able to repro the issue

>  Can you also add a log here?

I might be able to, but it's just we build our app on CI, so I will need to build locally which I don't have access to signing certificates, but I will give it a try. Since this issue is only happening on our prod build it's hard to debug.

**Comment by ozgurrgul** [comment] 2024-10-25 10:44
Apart from that there is another issue that is preventing me to debug above. 

We noticed that, recently when a user selects `Trust wallet` or any other wallet from the list, the wallet doesn't open to initiate a connection. Or when you open the wallet manually, it doesn't have any indication of WC connection too, so it gets stuck on `ConnectingView`. `Try again` button doesn't work as well. 

I put a log here since I am able to repro locally:

<img width="680" alt="image" src="https://github.com/user-attachments/assets/9c23698a-2ea5-4938-96d8-4d1382726f88">

<img width="796" alt="image" src="https://github.com/user-attachments/assets/3a877287-becf-4128-ae0b-1fe43ce3e67e">

<img width="546" alt="image" src="https://github.com/user-attachments/assets/0dd90c83-21e0-4ea9-bc54-96e4e902acf2">


So it seems `await ConnectionController.state.wcPromise;` waits indefinitely? and `console.log("initializeConnection 3")` doesn't get called into logs hence it doesn't continue to execute in the codeblock. 

Is it possible to check this too?

**Comment by ignaciosantise** [comment] 2024-10-31 17:30
hey @ozgurrgul 👋 sorry for the delay. Can you check if the QR code is generated? Open the modal -> All Wallets -> QR Code button at top right. Because i think you have an issue when trying to generate the connection uri

Some questions:
* Does `WALLET_CONNECT_PROJECT_ID` contain the project id? can you check that is not null?
* Did you add any bundle_id in your Cloud dashboard?

**Comment by ozgurrgul** [comment] 2024-11-04 08:48
> Does WALLET_CONNECT_PROJECT_ID contain the project id? can you check that is not null?

It contains the correct project id (otherwise, WC doesn't show any wallets).

> Did you add any bundle_id in your Cloud dashboard?

Yes, we have 3 bundle ids added in the Reown dashboard (for prod, staging, dev).

**Comment by ignaciosantise** [comment] 2024-11-04 14:38
@ozgurrgul if you go to the QR view, does the code load?

**Comment by ozgurrgul** [comment] 2024-11-04 14:59
@ignaciosantise  It's hanging on loading/blinking state and QR code doesn't load

**Comment by ignaciosantise** [comment] 2024-11-04 15:58
@ozgurrgul okey, then the issue is when trying to connect to the socket.

* Do you see any error related to sockets?
* Are you using a VPN? if so, can you check turning it off?
* Can you create a new project id and test? (without setting bundle ids)

**Comment by ignaciosantise** [comment] 2024-11-04 17:15
okey good, it might be related to the bundleIds validation. Can you go to your original Cloud project and add the bundleIds in the allowed domains list?

**Comment by ozgurrgul** [comment] 2024-11-04 17:18
Adding bundle ids to domain list like this? Yes it worked for the original project

<img width="987" alt="image" src="https://github.com/user-attachments/assets/9d40d61d-55c8-4380-9593-2e4e7dbe655e">

**Comment by ignaciosantise** [comment] 2024-11-04 17:19
Amazing! The Cloud team is already aware of this issue, i'll ping them again. But this workaround will make your project work 🤝

**Comment by ozgurrgul** [comment] 2024-11-04 23:22
> Guess we can close the issue?

Unfortunately we can't yet, it seems.

So there are 2 different issues:

1. Excessive amount of redirections to `TrustWallet` etc (the original issue)
2. When a user selects `TrustWallet` etc from the list, the app doesn't respond

The above `domain` workaround only fixed second item (and the original issue is now visible and still persists). The fix also introduces another issue for our prod builds, which walletConnect list is empty:

![WhatsApp Image 2024-11-04 at 23 12 07](https://github.com/user-attachments/assets/aa016d27-eb35-4393-b7cc-91196e82da13)

So, to summary, when we add the domain from dashboard, the the issue:

- We can click on the `TrustWallet` or any other wallet and it works
- I was able to interact with `TrustWallet` and it still tried to open it too many times

Now:w
- After the dashboard fix, wallet list is empty in our prod build or local development which there is no wallet to click. There was initially wallets visible, but now I can't see any wallet item anymore 

Relevant log:
![WhatsApp Image 2024-11-05 at 00 21 58](https://github.com/user-attachments/assets/865d76b2-1e60-43d1-803f-214b584f5e9b)

**Comment by ignaciosantise** [comment] 2024-11-05 15:13
@ozgurrgul the wallet list should be solved now, we had an issue recently -> https://status.reown.com/incidents/n059gtnp0jvs

**Comment by ignaciosantise** [comment] 2024-11-05 15:16
> I was able to interact with TrustWallet and it still tried to open it too many times

So this issue keeps happening?

**Comment by ozgurrgul** [comment] 2024-11-06 09:10
Ah I see, that timing of the incident was very coincident.  

> So this issue keeps happening?

I checked our build and the issue seem to be disappeared. Thanks for all the help!

**Comment by ignaciosantise** [comment] 2024-11-06 13:06
Amazing 🎉 I'm closing the issue then 🤝

**Closed by ignaciosantise** 2024-11-06 13:06 UTC
Labels: bug
